name: CI

on:
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup wasm-pack
        run: cargo install wasm-pack
      - name: Build silang-wasm
        run: wasm-pack build
        working-directory: silang-wasm

      - name: Setup
        run: yarn install
      - name: Build
        run: yarn build
      - name: Export
        run: yarn export
